on:
  # workflow_run:
  #   workflows: ['CI']
  #   types: [completed]
  push:
    tags:
      - 'release-v*' # Push events to matching release-v*, i.e. release-v1.0, release-v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get package.json version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PKG_SECRET_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: release-v${{ steps.extract_version.outputs.version }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: ${{ contains(steps.extract_version.outputs.version, '-pre') }}
