name: 'Packages cleanup'

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: 'Name of the package'
        default: 'template'
        required: true
        type: choice
        options:
          - 'template'
      packagesCount:
        description: 'Number of oldest packages to delete'
        required: true
        default: '5'
        type: choice
        options:
          - '1'
          - '5'
          - '10'
          - '15'
          - '20'
          - '30'

jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v3
        with:
          package-name: ${{ inputs.packageName }}
          num-old-versions-to-delete: ${{ inputs.packagesCount }}
